Repository mlabs-haskell/apropos, pull requests merged in 2022-04, with the labels that each got.

#17 Delegate hie yaml functions to cabal file.
  flake.nix
  hie.yaml
Labels: enhancement

#12 Brian/rational
  apropos.cabal
  examples/Main.hs
  examples/Spec/IntEither.hs
  examples/Spec/Rational.hs
  flake.nix
  src/Apropos.hs
  src/Apropos/HasAbstractions.hs
  src/Apropos/HasPermutationGenerator.hs
  src/Apropos/HasPermutationGenerator/Abstraction.hs
  src/Apropos/HasPermutationGenerator/Contract.hs
  src/Apropos/HasPermutationGenerator/Morphism.hs
  src/Apropos/LogicalModel.hs
Labels: enhancement

#20 Added type signatures to instance methods in README
  README.md
Labels: documentation

#15 Fraser/attempt fix shrink misbehaviour
  apropos.cabal
  examples/Spec/Int.hs
  examples/Spec/Rational.hs
  examples/Spec/TicTacToe/LocationSequence.hs
  examples/Spec/TicTacToe/MoveSequence.hs
  examples/Spec/TicTacToe/PlayerSequence.hs
  src/Apropos.hs
  src/Apropos/Gen.hs
  src/Apropos/Gen/BacktrackingTraversal.hs
  src/Apropos/Gen/Enumerate.hs
  src/Apropos/Gen/Range.hs
  src/Apropos/HasParameterisedGenerator.hs
  src/Apropos/HasPermutationGenerator.hs
  src/Apropos/HasPermutationGenerator/Morphism.hs
  src/Apropos/Pure.hs
Labels: bug
